### ISSUE TITLE
Account Create: Ignore Local Nameservers

### ISSUE THREAD

**Issue by ddarbyson** [site5/lumberg#105]
I often find when creating new accounts, there is no option to specify cPanels "Use the nameservers specified by the Domain's Registrar" functionality.

<img width="843" alt="screenshot 2015-10-31 22 11 13" src="https://cloud.githubusercontent.com/assets/1116416/10866903/8f239944-801c-11e5-839f-29f29828d4f8.png">

Defaulting to the domains current set nameservers is often needed as accounts being created are frequently are using our legacy nameservers.

Can you add this option?

```ruby
Lumberg::Whm::Server.new(...).account.create(
  :ignore_local_ns => true
)
```

**Comment by boone** [comment]
Hi @ddarbyson, it looks like you can enable this by passing in `useregns: true, hasuseregns: true` with your account creation options. You can pass in any of the parameters shown in the [WHM API doc](https://documentation.cpanel.net/display/SDK/WHM+API+1+Functions+-+createacct).

**Comment by ddarbyson** [comment]
Awesome... thanks for pointing me in the right direction. 

Keep up the great work. This gem is a huge time saver for us.

**Comment by boone** [comment]
@ddarbyson glad to help!
