### ISSUE TITLE
Unable to connect to cpanel api at port: 2807

### ISSUE THREAD

**Issue by wadoodk** [site5/lumberg#106]
Lumberg::WhmConnectionError: xxxxxxxxxxxx.com is either unavailable or is not currently accepting requests. Please try again in a few minutes.

**Comment by boone** [comment]
@wadoodk can you verify that your WHM server is actually running on that port? [Here is the code that raises this error.](https://github.com/site5/lumberg/blob/master/lib/lumberg/whm/server.rb#L260-L263) It is caused by a basic connection failure or a timeout.

**Comment by boone** [comment]
Closing - feel free to re-open this if there's still a problem.
